import { createContext, useContext, useState } from "react";

const TRANSLATIONS = {
  fr: {
    /* ── Navbar ── */
    home: "Accueil", catalog: "Catalogue", contact: "Contact", blog: "Blog & Ressources",
    login: "Connexion", logout: "Déconnexion", join: "Rejoindre", myAccount: "Mon Compte",
    langLabel: "Langue",

    /* ── Hero ── */
    heroBadge: "Plateforme UGC #1 au Maroc",
    heroEscrow: "🔒 Paiement Sécurisé",
    heroTitle1: "Trouvez les Meilleurs",
    heroTitle2: "Créateurs UGC",
    heroTitle3: "pour votre marque.",
    heroSub: "Connectez-vous à des créateurs marocains vérifiés. Paiements sécurisés via escrow. Contenu UGC livré en jours, pas en semaines.",
    heroCta: "Parcourir les Créateurs",
    heroCtaContact: "Nous Contacter",
    statCreators: "Créateurs Vérifiés",
    statSatisfaction: "Satisfaction Client",
    statDelivery: "Livraison Moy.",

    /* ── Services ── */
    servicesBadge: "Pourquoi Creato",
    servicesTitle1: "Conçu pour les marques qui",
    servicesTitle2: "veulent des résultats.",
    servicesSub: "Tout ce dont vous avez besoin pour lancer, développer et mesurer vos campagnes UGC.",
    servicesCtaTitle: "Prêt à développer votre marque ?",
    servicesCtaSub: "Plus de 200 marques utilisent déjà Creato.",
    servicesCtaBtn: "Commencer Aujourd'hui",
    svc1: { title: "Créateurs Vérifiés", desc: "Chaque créateur passe un processus de vérification strict avant de rejoindre notre réseau." },
    svc2: { title: "UGC Axé Performance", desc: "Contenu optimisé pour convertir avec un vrai ROI, pas que des métriques de vanité." },
    svc3: { title: "Tarification Transparente", desc: "Pas de frais cachés. Sachez exactement ce que vous payez avant le lancement." },
    svc4: { title: "Droits d'Utilisation", desc: "Licences claires incluses pour le paid et l'organique." },
    svc5: { title: "Livraison Rapide", desc: "Vidéos prêtes pour campagne en 7 jours ou moins." },
    svc6: { title: "Support Dédié", desc: "Notre équipe gère la coordination et la mise en place de campagne." },

    /* ── Portfolio ── */
    portfolioBadge: "Top Créateurs",
    portfolioTitle1: "Rencontrez",
    portfolioTitle2: "l'élite.",
    portfolioCta: "Voir Tous les Créateurs",
    portfolioViewProfile: "Voir le Profil →",

    /* ── About / Comparison ── */
    aboutBadge: "Comparaison",
    aboutTitle1: "Creato vs.",
    aboutTitle2: "Les Alternatives",
    aboutSub: "Découvrez pourquoi 200+ marques ont choisi Creato.",
    aboutNote: "* Basé sur une enquête indépendante de 150 directeurs marketing — 2025",
    colFeature: "Fonctionnalité",
    row1: "Créateurs vérifiés", row2: "Paiement escrow sécurisé",
    row3: "Suivi de performance", row4: "Droits d'utilisation complets",
    row5: "Livraison 7 jours", row6: "Support dédié",

    /* ── Contact ── */
    contactTitle1: "Prêt à",
    contactTitle2: "Démarrer ?",
    contactSub: "Que vous soyez une marque ou un créateur, notre équipe est prête à propulser votre vision.",
    contactPhone: "TÉLÉPHONE", contactEmail: "EMAIL",
    contactLocation: "LOCALISATION", contactHours: "HORAIRES",
    contactHoursVal: "Lun – Ven, 9h – 18h",
    contactLive: "Support en Direct 24/7",
    contactLiveSub: "Obtenez des réponses instantanées de notre équipe.",
    contactFormTitle: "Écrivez-nous",
    contactName: "NOM COMPLET", contactEmailLabel: "ADRESSE EMAIL",
    contactSubject: "SUJET DU PROJET", contactMessage: "VOTRE MESSAGE",
    contactNamePh: "Jean Dupont", contactEmailPh: "jean@exemple.com",
    contactSubjectPh: "Comment pouvons-nous collaborer ?",
    contactMsgPh: "Décrivez votre vision...",
    contactBtn: "Lancer le Projet",

    /* ── Blog ── */
    blogBadge: "Centre de Ressources",
    blogTitle1: "Inside",
    blogSub: "Le pouls de l'UGC au Maroc. Tendances, stratégies et succès.",
    blogSearchPh: "Explorer sujets, tendances ou créateurs...",
    blogEmptyTitle: "Calme sur le plateau...",
    blogEmptySub: "Aucun article trouvé. Essayez un autre thème ou réinitialisez.",
    blogReset: "Réinitialiser",

    /* ── Footer ── */
    footerTagline: "La plateforme #1 pour connecter les marques aux créateurs UGC vérifiés.",
    footerNav: "Navigation", footerContact: "Contact",
    footerStart: "Démarrer un Projet →",
    footerPrivacy: "Politique de Confidentialité", footerTerms: "Conditions d'Utilisation",
    footerCopy: "© 2026 Creato — Tous droits réservés.",

    /* ── Catalog ── */
    catalogBadge: "Talents Mondiaux",
    catalogTitle1: "Élevez votre marque avec des créateurs",
    catalogTitle2: "élite.",
    catalogSub: "Accédez au top 1% des créateurs UGC au Maroc. Vérifiés, professionnels.",
    catalogSearchPh: "Rechercher nom, niche ou ville...",
    catalogReset: "Réinitialiser",
    filterTitle: "FILTRES", filterLocation: "LOCALISATION", filterNiche: "NICHE", filterPrice: "PRIX (MAD)",
    filterMinPh: "Min ex. 300", filterMaxPh: "Max ex. 1500",
    sortBy: "Trier par", sortRec: "Recommandé", sortPriceLow: "Prix: Croissant",
    sortPriceHigh: "Prix: Décroissant", sortName: "Nom: A–Z",
    creators: "créateurs trouvés",
    catalogEmptyTitle: "Aucun créateur trouvé",
    catalogEmptySub: "Ajustez vos filtres ou votre recherche.",
    catalogEmptyBtn: "Réinitialiser les Filtres",
  },

  en: {
    home: "Home", catalog: "Catalog", contact: "Contact", blog: "Blog & Resources",
    login: "Login", logout: "Logout", join: "Join", myAccount: "My Account",
    langLabel: "Language",
    heroBadge: "Morocco's #1 UGC Platform",
    heroEscrow: "🔒 Escrow Protected",
    heroTitle1: "Find the Best",
    heroTitle2: "UGC Creators",
    heroTitle3: "for your brand.",
    heroSub: "Connect with verified Moroccan creators. Secure escrow payments. Performance-focused UGC delivered in days, not weeks.",
    heroCta: "Browse Creators",
    heroCtaContact: "Get in Touch",
    statCreators: "Verified Creators",
    statSatisfaction: "Client Satisfaction",
    statDelivery: "Avg. Delivery",
    servicesBadge: "Why Creato",
    servicesTitle1: "Built for brands that",
    servicesTitle2: "demand results.",
    servicesSub: "Everything you need to launch, scale, and measure UGC campaigns — in one place.",
    servicesCtaTitle: "Ready to scale your brand?",
    servicesCtaSub: "Join 200+ brands already growing with Creato.",
    servicesCtaBtn: "Get Started Today",
    svc1: { title: "Verified Creators", desc: "Every creator goes through a strict verification process before joining our network." },
    svc2: { title: "Performance-Focused UGC", desc: "Content optimized to convert with real ROI, not just vanity metrics." },
    svc3: { title: "Transparent Pricing", desc: "No hidden fees. Know exactly what you pay for before launch." },
    svc4: { title: "Full Usage Rights", desc: "Clear licenses included for paid and organic channels." },
    svc5: { title: "Fast Delivery", desc: "Campaign-ready videos in 7 days or less." },
    svc6: { title: "Dedicated Support", desc: "Our team handles creator coordination and campaign setup." },
    portfolioBadge: "Top Creators",
    portfolioTitle1: "Meet the",
    portfolioTitle2: "elite.",
    portfolioCta: "View All Creators",
    portfolioViewProfile: "View Profile →",
    aboutBadge: "Comparison",
    aboutTitle1: "Creato vs.",
    aboutTitle2: "The Rest",
    aboutSub: "See why 200+ brands chose Creato over traditional alternatives.",
    aboutNote: "* Based on independent survey of 150 brand managers — 2025",
    colFeature: "Feature",
    row1: "Verified creators", row2: "Secure escrow payment",
    row3: "Performance tracking", row4: "Full usage rights",
    row5: "Fast 7-day delivery", row6: "Dedicated support",
    contactTitle1: "Ready to",
    contactTitle2: "Start?",
    contactSub: "Whether you're a brand or creator, our elite team is ready to scale your vision.",
    contactPhone: "PHONE", contactEmail: "EMAIL",
    contactLocation: "LOCATION", contactHours: "WORKING HOURS",
    contactHoursVal: "Mon – Fri, 9am – 6pm",
    contactLive: "Live Support 24/7",
    contactLiveSub: "Get instant answers from our dedicated expert team.",
    contactFormTitle: "Drop us a line",
    contactName: "FULL NAME", contactEmailLabel: "EMAIL ADDRESS",
    contactSubject: "PROJECT SUBJECT", contactMessage: "TELL US EVERYTHING",
    contactNamePh: "John Doe", contactEmailPh: "john@example.com",
    contactSubjectPh: "How can we collaborate?", contactMsgPh: "Describe your vision...",
    contactBtn: "Start Project",
    blogBadge: "Knowledge Hub",
    blogTitle1: "Inside",
    blogSub: "The pulse of UGC in Morocco. Trends, strategies and success stories.",
    blogSearchPh: "Explore topics, trends or creators...",
    blogEmptyTitle: "Quiet on set...",
    blogEmptySub: "No articles found. Try a different niche or reset to see everything.",
    blogReset: "Reset Library",
    footerTagline: "Morocco's #1 platform for connecting brands with verified UGC creators.",
    footerNav: "Navigation", footerContact: "Contact",
    footerStart: "Start a Project →",
    footerPrivacy: "Privacy Policy", footerTerms: "Terms of Service",
    footerCopy: "© 2026 Creato — All rights reserved.",
    catalogBadge: "World-Class Talents",
    catalogTitle1: "Elevate your brand with",
    catalogTitle2: "elite",
    catalogSub: "Access the top 1% of UGC creators in Morocco. Verified, professional.",
    catalogSearchPh: "Search name, niche or city...",
    catalogReset: "Reset",
    filterTitle: "FILTERS", filterLocation: "LOCATION", filterNiche: "NICHE", filterPrice: "PRICE (MAD)",
    filterMinPh: "Min e.g. 300", filterMaxPh: "Max e.g. 1500",
    sortBy: "Sort by", sortRec: "Recommended", sortPriceLow: "Price: Low to High",
    sortPriceHigh: "Price: High to Low", sortName: "Name: A–Z",
    creators: "creators found",
    catalogEmptyTitle: "No creators found",
    catalogEmptySub: "Try adjusting your filters or search term.",
    catalogEmptyBtn: "Reset All Filters",
  },

  ar: {
    home: "الرئيسية", catalog: "الفهرس", contact: "التواصل", blog: "المدونة",
    login: "تسجيل الدخول", logout: "تسجيل الخروج", join: "انضم", myAccount: "حسابي",
    langLabel: "اللغة",
    heroBadge: "منصة UGC رقم 1 في المغرب",
    heroEscrow: "🔒 دفع آمن",
    heroTitle1: "اعثر على أفضل",
    heroTitle2: "منشئي المحتوى",
    heroTitle3: "لعلامتك التجارية.",
    heroSub: "تواصل مع منشئي محتوى مغاربة موثقين. مدفوعات آمنة. محتوى UGC يُسلَّم في أيام.",
    heroCta: "تصفح المنشئين",
    heroCtaContact: "تواصل معنا",
    statCreators: "منشئون موثقون",
    statSatisfaction: "رضا العملاء",
    statDelivery: "متوسط التسليم",
    servicesBadge: "لماذا Creato",
    servicesTitle1: "مُصمَّم للعلامات التي",
    servicesTitle2: "تريد نتائج.",
    servicesSub: "كل ما تحتاجه لإطلاق وتطوير وقياس حملات UGC في مكان واحد.",
    servicesCtaTitle: "هل أنت مستعد لتوسيع علامتك التجارية؟",
    servicesCtaSub: "انضم إلى 200+ علامة تجارية تنمو مع Creato.",
    servicesCtaBtn: "ابدأ اليوم",
    svc1: { title: "منشئون موثقون", desc: "يجتاز كل منشئ عملية توثيق صارمة قبل الانضمام." },
    svc2: { title: "UGC يركز على الأداء", desc: "محتوى محسّن للتحويل بعائد استثمار حقيقي." },
    svc3: { title: "تسعيرة شفافة", desc: "لا رسوم مخفية. اعرف ما تدفعه قبل الإطلاق." },
    svc4: { title: "حقوق استخدام كاملة", desc: "تراخيص واضحة للقنوات المدفوعة والعضوية." },
    svc5: { title: "تسليم سريع", desc: "مقاطع فيديو جاهزة للحملة في 7 أيام أو أقل." },
    svc6: { title: "دعم مخصص", desc: "يتولى فريقنا تنسيق المنشئين وإعداد الحملة." },
    portfolioBadge: "أبرز المنشئين",
    portfolioTitle1: "تعرف على",
    portfolioTitle2: "النخبة.",
    portfolioCta: "عرض جميع المنشئين",
    portfolioViewProfile: "عرض الملف →",
    aboutBadge: "مقارنة",
    aboutTitle1: "Creato مقابل",
    aboutTitle2: "البدائل",
    aboutSub: "اكتشف لماذا اختارت 200+ علامة تجارية Creato.",
    aboutNote: "* بناءً على استطلاع مستقل لـ 150 مدير تسويق — 2025",
    colFeature: "الميزة",
    row1: "منشئون موثقون", row2: "دفع escrow آمن",
    row3: "تتبع الأداء", row4: "حقوق استخدام كاملة",
    row5: "تسليم 7 أيام", row6: "دعم مخصص",
    contactTitle1: "هل أنت مستعد",
    contactTitle2: "للبدء؟",
    contactSub: "سواء كنت علامة تجارية أو منشئاً، فريقنا مستعد لتحقيق رؤيتك.",
    contactPhone: "الهاتف", contactEmail: "البريد الإلكتروني",
    contactLocation: "الموقع", contactHours: "ساعات العمل",
    contactHoursVal: "الاثنين – الجمعة، 9ص – 6م",
    contactLive: "دعم مباشر 24/7",
    contactLiveSub: "احصل على إجابات فورية من فريق الخبراء.",
    contactFormTitle: "راسلنا",
    contactName: "الاسم الكامل", contactEmailLabel: "البريد الإلكتروني",
    contactSubject: "موضوع المشروع", contactMessage: "أخبرنا كل شيء",
    contactNamePh: "محمد الأمين", contactEmailPh: "mohammed@example.com",
    contactSubjectPh: "كيف يمكننا التعاون؟", contactMsgPh: "صِف رؤيتك...",
    contactBtn: "بدء المشروع",
    blogBadge: "مركز المعرفة",
    blogTitle1: "داخل",
    blogSub: "نبض UGC في المغرب. اتجاهات واستراتيجيات وقصص نجاح.",
    blogSearchPh: "استكشف مواضيع أو منشئين...",
    blogEmptyTitle: "هادئ في الاستوديو...",
    blogEmptySub: "لم يُعثر على مقالات. جرب بحثاً مختلفاً.",
    blogReset: "إعادة تعيين",
    footerTagline: "المنصة الأولى لربط العلامات التجارية بمنشئي UGC الموثقين.",
    footerNav: "التنقل", footerContact: "التواصل",
    footerStart: "بدء مشروع →",
    footerPrivacy: "سياسة الخصوصية", footerTerms: "شروط الخدمة",
    footerCopy: "© 2026 Creato — جميع الحقوق محفوظة.",
    catalogBadge: "مواهب عالمية",
    catalogTitle1: "ارتقِ بعلامتك مع منشئين",
    catalogTitle2: "نخبة.",
    catalogSub: "الوصول إلى أفضل 1% من منشئي UGC في المغرب. موثقون ومحترفون.",
    catalogSearchPh: "ابحث بالاسم أو النيش أو المدينة...",
    catalogReset: "إعادة تعيين",
    filterTitle: "الفلاتر", filterLocation: "الموقع", filterNiche: "النيش", filterPrice: "السعر (MAD)",
    filterMinPh: "الحد الأدنى", filterMaxPh: "الحد الأقصى",
    sortBy: "ترتيب حسب", sortRec: "موصى به", sortPriceLow: "السعر: تصاعدي",
    sortPriceHigh: "السعر: تنازلي", sortName: "الاسم: أ–ي",
    creators: "منشئ بُحث عنه",
    catalogEmptyTitle: "لا منشئين",
    catalogEmptySub: "حاول تعديل الفلاتر أو البحث.",
    catalogEmptyBtn: "إعادة تعيين الفلاتر",
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState("fr");
  const t = TRANSLATIONS[lang];
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

// eslint-disable-next-line react-refresh/only-export-components
export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used inside LanguageProvider");
  return ctx;
}
